name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]



jobs:
  build_linux:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libfcitx-qt5-dev fcitx-frontend-qt5
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtwebengine'

    - name: do build
      run: qmake PowerVelo3.pro

    
    - uses: actions/upload-artifact@v1
      with:
        name: linux
        path: build/artifact 

  build_windows:
    runs-on: windows-latest

    steps:
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
    - name: checkout
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtwebengine'

    - name: do build
      run: qmake PowerVelo3.pro
    
    - uses: actions/upload-artifact@v1
      with:
        name: windows
        path: build\artifact 


  build_mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts qtwebengine'
    - name: do build
      run: qmake PowerVelo3.pro
    
    - uses: actions/upload-artifact@v1
      with:
        name: macos
        path: build/artifact 
