name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Linux Environment Setup
      run: |
        DEBIAN_FRONTEND=noninteractive apt update && apt install sudo software-properties-common --yes
        DEBIAN_FRONTEND=noninteractive sudo apt-get update --yes
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.6-bionic
        sudo DEBIAN_FRONTEND=noninteractive apt install python3-pip --yes
        sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq qt5-default qt512base qt512tools libqwt-qt5-6 qt512serialport qt512svg qt512multimedia qt512connectivity qt512webengine qt512charts-no-lgpl qt512networkauth-no-lgpl qt512translations
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        modules: 'qtcharts qtwebengine'

    - name: Create Makefile
      run: 
        qmake PowerVelo.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: build/

  build_windows:
    runs-on: windows-latest

    steps:
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        modules: 'qtcharts qtwebengine'

    - name: Create Makefile
      run: 
        qmake PowerVelo.pro -spec winrt-x64-msvc2017
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: build\ 


  build_mac:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: QT Environment Setup
      run: |
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
      brew install qt5
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        modules: 'qtcharts qtwebengine'
    - name: Create Makefile
      run: 
        qmake PowerVelo.pro
    - name: Run MakeFile
      run: make
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: build/ 
