name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-18.04

    steps:
    - name: Install dependencies
      uses: actions/checkout@v2
      run: |
        DEBIAN_FRONTEND=noninteractive apt update && apt install sudo software-properties-common --yes
        DEBIAN_FRONTEND=noninteractive sudo apt-get update --yes
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.6-bionic
        sudo DEBIAN_FRONTEND=noninteractive apt install python3-pip --yes
        sudo DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq qt5-default qt514base qt514tools qt514serialport qt514svg qt514multimedia qt514connectivity qt514webengine qt514charts-no-lgpl qt514networkauth-no-lgpl qt514translations
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        modules: 'qtcharts qtwebengine'

    - name: do build
      run: 
        qmake PowerVelo.pro
        make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: build/

  build_windows:
    runs-on: windows-latest

    steps:
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        modules: 'qtcharts qtwebengine'

    - name: do build
      run:
        qmake PowerVelo.pro
        make
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: build\ 


  build_mac:
    runs-on: macos-latest

    steps:
    - name: checkout
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.8.0
      with:
        modules: 'qtcharts qtwebengine'
    - name: do build
      run:
        qmake PowerVelo.pro
        make
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: macos
        path: build/ 
